id: P438322E2
initial_creation_type: ocr
source_metadata:
  volumes:
    59e5a54060a147bca01517b4df67a16a:
      base_file: v064.txt
      image_group_id: I1PD95909
      title: བསྒོམ་རིམ་ཐ་མ།
      total_pages: 1902
      volume_number: 64
